import { Router } from "express";
import userRouter from "./userRouter";
import { validateToken } from "../middlewares/validateToken";
import credentialRouter from "./credentialRouter";
import notesRouter from "./notesRouter";
import cardsRouter from "./carsdRouter";
import wifiRouter from "./wifiRouter";
const router = Router();
router.use(userRouter);
router.use(validateToken);
router.use(credentialRouter);
router.use(notesRouter);
router.use(cardsRouter);
router.use(wifiRouter);
export default router;
