import { Router } from "express";
import userRouter from "./userRouter";
import { validateToken } from "../middlewares/validateToken";
import credentialRouter from "./credentialRouter";
import notesRouter from "./notesRouter";
const router = Router();
router.use(userRouter);
router.use(validateToken);
router.use(credentialRouter);
router.use(notesRouter);
export default router;
